### ISSUE TITLE
game_module classes

### ISSUE THREAD

**Issue by knightrix** [Ninroot-Eater/Discord-Bot#1]
In Character class ..
https://github.com/Ninroot-Eater/Discord-Bot/blob/7759bf300b43f13df169385d0c8c9e8192a3d948/game_module.py#L21

status is truthy so you can do 
```   python
if status:
      self.status = status
else:
      self.status = "alive"
```
or better yet, you can set your default value to 'alive' in your parameter directly.
``` python
def __init__(self,name , id, hp, attk, defn, first_attr, second_attr, first_des, second_des,
                 image_file, gender, cost, status = 'alive')
```
and then just set status like all other attributes. So you do not need if/else check anymore
```python
self.status = status
```

Similarly in Player class
https://github.com/Ninroot-Eater/Discord-Bot/blob/7759bf300b43f13df169385d0c8c9e8192a3d948/game_module.py#L43
You can set default values directly in your arguments list when appropriate and also update if statements when checking truthy or falsey values. 
``` python
if selected_cha is None:
```
can be replaced with
``` python
if !selected_cha:
```

**Comment by ninnroot** [comment]
I see!
Yea, the Player class is a little too messy for my liking. I kinda thought
about making it more organised. But, the code works so, I just let it be.

**Comment by ninnroot** [comment]
won't fix:)
